### ISSUE TITLE
Erro no teste?

### ISSUE THREAD

**Issue by Lucitar** [ProfRonan/matrizes-e-vetores-Lucitar#2]
Fiz o commit após executar os teste automatizados no meu pc e tudo funcionou. Mas quando executou no github apresentou um erro que não compreendi. Poderia verificar onde está o problema?

**Comment by SeuRonao** [comment]
O erro é sobre a formatação.

![image](https://github.com/ProfRonan/matrizes-e-vetores-Lucitar/assets/22750712/30455c46-1680-4e36-8e57-bf8007a83c63)

Todos os testes passaram de verdade pois aparece o 100/100.

Para passar na formatação (algo que não vale nota nessa atividade), basta usar o black o isort e o pylint.
